server:
  port: 8000

spring:
  profiles:
    active: local
  application:
    name: demo
JWT:
  secret-key: G8f9kA8g9DxZ/3v7H2g1V6f9l3A1m6YdP3B7h4Q6l8c=
  access-expiration-time: 600 # 10? 600
  refresh-expiration-time: 864000 # 10? 864000
logging.level:
  org.hibernate.SQL: debug
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**